# Generated by Django 2.1.5 on 2019-02-13 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nostaldja', '0003_auto_20190213_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fads',
            name='image_url',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='fads',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
